### ISSUE TITLE
关于使用该框架在页面网络请求的问题

### ISSUE THREAD

**Issue by slow-sheep** [yaoxfly/vue3-simple-frame#1]
你好，首先谢谢你的框架，对我来说非常有用。

我遇到了一个问题，在页面所需网络请求已经完成之后，图片没有加载出来，图片的地址是网络地址，并且我可以在vue devtools插件里边看见图片地址是有数据的。然后我在VScode编辑器里边对页面文件的注释修改一下页面会显示图片，这时我发现可以在浏览器控制台网络选项在可以看到关于图片的网络请求。我之前使用vue2可以直接加载出来，不知道是哪里出了问题。

附件图片顺序：1.页面加载之后没有显示图片 ，但是devtools中显示有数据
                          2.修改一下注释后，.图片这时有网络请求，并且可以看到图片
1.![QQ截图20221206103204](https://user-images.githubusercontent.com/117260282/205794727-2fde30ed-5b54-44a5-b611-c1259768a5e1.png)
2.![QQ截图20221206103438](https://user-images.githubusercontent.com/117260282/205794741-71497898-597f-421d-9e9d-6cb93a4cee40.png)

**Comment by yaoxfly** [comment]
![1670315954973](https://user-images.githubusercontent.com/44956835/205861963-da5124c5-eaec-44c6-a1dd-72c49f609614.jpg)

我这边是能正常展示的

这不是框架问题，应该是写法问题，异步获取图片要用ref或reactive来定义图片，让数据双向绑定     范例 ：

```js
const img = ref('')
    //模拟异步获取
    setTimeout(() => {
      img.value = getImage('https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.ixintu.com%2Fdownload%2Fjpg%2F201912%2F65883347c85b5c74703a80edc8dfb72a.jpg%21con&refer=http%3A%2F%2Fimg.ixintu.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1672906787&t=10151c361baf245b2ad18c77d3e3a648')
    }, 2000)

<img  :src='img' / >
```

**Comment by slow-sheep** [comment]
谢谢谢谢，我试了试vite的new url api对于我没有效果。不过使用在定义的时候使用reactive，网络请求完数据之后使用push方法添加到数组中，就可以加载出来。同时我也参考了一下这篇，https://juejin.cn/post/7108605278953668639
![QQ截图20221206191638](https://user-images.githubusercontent.com/117260282/205897464-3807a534-bb54-4018-b8a8-396296b4b710.png)
![QQ截图20221206191719](https://user-images.githubusercontent.com/117260282/205897469-16b4f850-dd28-4c8f-b58f-c08c7bf0b64d.png)

**Comment by yaoxfly** [comment]
嗯 ，我再仔细看时，已经意识到有可能是双向绑定的问题了，后面的回答我也进行了修正。 对了，如果你要上生产部署的时候有用到二级目录 ，需要修改下router的配置。我当前修改还没上传。
```js
import { createRouter, createWebHistory } from 'vue-router'
import routes from './routes'
const router = createRouter({
  //   history: createWebHistory(),  //旧的配置 
  history: createWebHistory(import.meta.env.BASE_URL),  //新的配置
  routes
})
export default router
```

**Comment by yaoxfly** [comment]
问题已解决，我关闭了
